#!/usr/bin/env node

const ShellSpec = require('..');

const spec = {
    kind: 'shell',
    spec: {
        command: 'echo',
        args: [
            {
                name: 'args',
                type: 'values',

                // here we add a `required` property to the spec which indicate the user should be prompted if this config value is missing
                required: true,
                message: 'What values would you like to echo?'
            }
        ]
    }
};

const echo = ShellSpec(spec);

(async () => console.log(await echo.promptedArgv()))();
